In [4]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# For simplicity, we will consider only two classes
X = X[y != 2]  # Remove class '2'
y = y[y != 2]  # Only classes '0' and '1'

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Choose an instance to explain
instance_to_explain = X_test[0]
print("Instance to explain:", instance_to_explain)

# Predict the probability for the chosen instance
def model_predict(instance):
    return model.predict_proba([instance])[0]

def calculate_shapley_values(model, instance, X_train):
    num_features = len(instance)
    shap_values = np.zeros(num_features)
    print("shapval")
    print(shap_values)

    # Predict the baseline (average prediction for the positive class)
    baseline_prediction = np.mean([model_predict(x)[1] for x in X_train])  # Average over training data for class 1
    print("baseline")
    print(baseline_prediction)

    for i in range(num_features):
        # Create a modified instance with the i-th feature removed
        modified_instance = instance.copy()
        modified_instance[i] = 0  # Set the i-th feature to 0
        print("modified_instance")
        print(modified_instance)
        # Calculate the contribution of the i-th feature
        with_feature = model_predict(instance)[1]  # Get the probability of class 1
        without_feature = model_predict(modified_instance)[1]  # Get the probability of class 1
        print("with_feature")
        print(with_feature)
        print("without_feature")
        print(without_feature)
        # SHAP value contribution
        shap_values[i] = with_feature - without_feature
        print("shap_value")
        print(shap_values)
    return shap_values


# Calculate SHAP values for the chosen instance
shap_values = calculate_shapley_values(model, instance_to_explain, X_train)

# Print SHAP values
print("\nSHAP Values (Feature Importance):")
for i, feature in enumerate(iris.feature_names[:len(shap_values)]):
    print(f"{feature}: {shap_values[i]:.4f}")


Instance to explain: [6.  2.7 5.1 1.6]
shapval
[0. 0. 0. 0.]
baseline
0.5255
modified_instance
[0.  2.7 5.1 1.6]
shap_value
[0.01 0.   0.   0.  ]
modified_instance
[6.  0.  5.1 1.6]
shap_value
[0.01 0.   0.   0.  ]
modified_instance
[6.  2.7 0.  1.6]
shap_value
[0.01 0.   0.5  0.  ]
modified_instance
[6.  2.7 5.1 0. ]
shap_value
[0.01 0.   0.5  0.44]

SHAP Values (Feature Importance):
sepal length (cm): 0.0100
sepal width (cm): 0.0000
petal length (cm): 0.5000
petal width (cm): 0.4400
